spring.application.name=jewelry-marketplace

spring.datasource.url=jdbc:postgresql://localhost:5432/jewelry_db
spring.datasource.username=postgres
spring.datasource.password=2685
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.cache.type=redis
spring.cache.redis.time-to-live=600000

server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.secure=false
server.servlet.session.timeout=30m

logging.level.com.jewelry=DEBUG

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
